Repository yandex-cloud/docs, pull requests merged in 2021-11, with the labels that each got.

#231 Test commit, do not merge
  README.md
Labels: question, wontfix

#232 add link to Azure AD to other identity providers
  en/organization/add-federation.md
  ru/organization/add-federation.md
Labels: editorial

#229 Update ymq-trigger.md
  ru/functions/concepts/trigger/ymq-trigger.md
Labels: message-queue
